name: "Kogito Tooling :: Build chain."

on: [pull_request]

jobs:
  build-chain:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Build chain
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run build chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@tiagosflow
        with:
          starting-project: kiegroup/kogito-tooling
          definition-file: https://raw.githubusercontent.com/kiegroup/appformer/2b93e3d1728d4a65b7ee7b8d455b38d38948c466/.ci/kogito-tooling-definition.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

